VP-4688: Extend Contact with 'Title' field
VirtoCommerce/vc-demo-storefront pull request #18
Opened 2020-09-24 14:23 UTC by trueboroda

Allow editing and getting

2020-09-24 14:34 UTC, OlegoO approved these changes, later dismissed

2020-09-24 15:07 UTC, pushnitsa requested changes

2020-09-24 15:07 UTC, pushnitsa commented on VirtoCommerce.Storefront.Model/Customer/Contact.cs
Remove empty line

2020-09-24 15:07 UTC, pushnitsa commented on VirtoCommerce.Storefront.Model/Security/UserRegistration.cs
> +
Remove empty line

2020-09-24 15:07 UTC, pushnitsa commented on VirtoCommerce.Storefront/Domain/Customer/MemberConverter.cs
> +                Title = contactDto.Title
Add comma

2020-09-24 15:07 UTC, pushnitsa commented on VirtoCommerce.Storefront/Domain/Customer/MemberConverter.cs
> +                Title = userRegistration.Title
Add comma

2020-09-25 15:18 UTC, pushnitsa approved these changes

2020-09-25 15:25 UTC, merged