VDS-106: Fix wrang redirection at NoTheme and "Allow anonymus" disabled"
VirtoCommerce/vc-demo-storefront pull request #44
Opened 2020-11-24 09:46 UTC by trueboroda

2020-11-24 13:44 UTC, pushnitsa requested changes

2020-11-24 13:44 UTC, pushnitsa commented on VirtoCommerce.Storefront/Filters/AnonymousUserForStoreAuthorizationFilter.cs
> +                && (action as string).Equals("NoTheme", StringComparison.InvariantCultureIgnoreCase);
Use strict cast and EqualsInvariant() extension

2020-11-24 13:44 UTC, pushnitsa commented on VirtoCommerce.Storefront/Filters/AnonymousUserForStoreAuthorizationFilter.cs
> +            var isItNoThemeAction = context.RouteData.Values.TryGetValue("controller", out var controller)
isNotThemeAction

2020-11-24 14:28 UTC, pushnitsa submitted a review, later dismissed

2020-11-26 07:03 UTC, pushnitsa approved these changes

2020-11-26 08:22 UTC, ilyawzrd approved these changes

2020-11-26 08:24 UTC, merged