VDS-749: Save Name and ImageUrl in configured Group entities for cart and order
VirtoCommerce/vc-demo-storefront pull request #54
Opened 2021-01-28 14:57 UTC by trueboroda

2021-01-28 15:00 UTC, Vectorfield4 approved these changes

2021-01-28 15:12 UTC, pushnitsa requested changes

2021-01-28 15:12 UTC, pushnitsa commented on VirtoCommerce.Storefront.Model/Cart/Demo/ConfiguredGroup.cs
> +        public ConfiguredGroup(int quantity, Currency currency, string productId, string name, string imageUrl) : this(quantity, currency, productId)
Why did you add another constructor?

2021-01-29 07:09 UTC, pushnitsa approved these changes

2021-02-01 07:42 UTC, merged