VDS-790: Load product parts of the configurable product with him
VirtoCommerce/vc-demo-storefront pull request #56
Opened 2021-02-03 10:47 UTC by trueboroda

2021-02-03 11:03 UTC, pushnitsa requested changes

2021-02-03 11:03 UTC, pushnitsa commented on VirtoCommerce.Storefront/Domain/Catalog/DemoCatalogService.cs
> +                cacheEntry.AddExpirationToken(CatalogCacheRegion.CreateChangeToken());
Add api changes token

2021-02-03 11:03 UTC, pushnitsa commented on VirtoCommerce.Storefront/Domain/Catalog/Demo/CatalogConverter.cs
> +            var result = new ProductPart()
remove ()

2021-02-03 11:06 UTC, pushnitsa requested changes

2021-02-03 11:06 UTC, pushnitsa commented on VirtoCommerce.Storefront/Domain/Catalog/DemoCatalogService.cs
> +                var searchPartsResultDto = await _demoCatalogApi.SearchAsync(new DemoProductPartSearchCriteria() { ConfiguredProductId = productId, Take = 1000 });
Take = int.maxValue

2021-02-03 11:06 UTC, Vectorfield4 requested changes

2021-02-03 11:06 UTC, Vectorfield4 commented on VirtoCommerce.Storefront/Domain/Catalog/DemoCatalogService.cs
> +            if (!products.IsNullOrEmpty())
Is `products=null` are viable value for this place? if not we can remove this condition.

2021-02-03 11:06 UTC, Vectorfield4 commented on VirtoCommerce.Storefront/Domain/Catalog/DemoCatalogService.cs
> +                    if(product.ProductType.EqualsInvariant("Configurable"))
You can move this condition to line 52 to reduce cognitive complexity. 
``` csharp
// Load product parts to configurable products
foreach(var product in products.Where(x => x.ProductType.EqualsInvariant("Configurable")))
```

2021-02-03 11:06 UTC, Vectorfield4 commented on VirtoCommerce.Storefront/Domain/Catalog/DemoCatalogService.cs
> +                }).ToArray();
Move select function to local function/method. It's hard to read.

2021-02-03 14:26 UTC, trueboroda commented on VirtoCommerce.Storefront/Domain/Catalog/DemoCatalogService.cs
> +            if (!products.IsNullOrEmpty())
Such behavior in the original method LoadProductDependencies.

2021-02-03 14:28 UTC, trueboroda commented on VirtoCommerce.Storefront/Domain/Catalog/DemoCatalogService.cs
> +            if (!products.IsNullOrEmpty())
https://github.com/VirtoCommerce/vc-demo-storefront/blob/e870ffc2c91d468fe7155065f022ba3a082c8ee1/VirtoCommerce.Storefront/Domain/Catalog/CatalogService.cs#L213

2021-02-03 15:59 UTC, Vectorfield4 approved these changes

2021-02-03 16:29 UTC, pushnitsa requested changes

2021-02-03 16:29 UTC, pushnitsa commented on VirtoCommerce.Storefront.Model/Catalog/Demo/ProductTypes.cs
> +        static public string Configurable { get; set; } = "Configurable";
replace property by constant

2021-02-03 16:29 UTC, pushnitsa commented on VirtoCommerce.Storefront.Model/Catalog/Specifications/ProductIsBuyableSpecification.cs
> +            return ( product.IsActive && product.IsBuyable && product.Price.ListPrice.Amount > 0 && product.ProductType != ProductTypes.Configurable )
Add unit tests to this method

2021-02-04 14:12 UTC, Vectorfield4 approved these changes

2021-02-04 14:45 UTC, pushnitsa approved these changes

2021-02-04 14:45 UTC, merged